### ISSUE TITLE
Unicode in README instead of LaTeX

### ISSUE THREAD

**Issue by rikhuijzer** [cgeoga/BesselK.jl#5]
Suggestion: with a bit of creativity, it should be possible to use Unicode to greatly improve the readability of the README. For example, see https://github.com/jbytecode/JMcDM/pull/31.

I would have suggested a PR for this repo already if \nu (ν) was available as subscript. That isn't the case unfortunately, so that's why a bit of creativity is needed. Would it be possible to use another character than ν so that the subscript would work out?

**Comment by cgeoga** [comment]
That is a good point. It might make sense to just use the normal `v` character. I'll given it a go in the README---is this the kind of update you had in mind? Thanks so much for taking a look at the repo and for your suggestions!

**Comment by rikhuijzer** [comment]
You’re welcome. Yes exactly! It’s much easier to read now!
